version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/assets:/code/assets
    ports:
      - "8080:8080"
