version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.DEV
    image: houselights_backend_dev
    volumes:
      - ./backend/src:/code
    environment:
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.DEV
    image: houselights_frontend_dev
    volumes:
      - ./frontend/assets:/code/assets
      - ./frontend/dist:/code/dist
    command: npm run devrun
  nginx:
    image: arm32v7/nginx
    volumes:
      - ./frontend/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8000:80"
    networks:
      - lightsnet
