version: '3'
services:
  backend:
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0
  frontend:
    command: npm run devrun
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
