version: '3'
services:
  backend:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: houselights_backend_prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0 --port=5000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: houselights_frontend_prod
    ports:
      - "80:80"
