version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
    command: gunicorn -w 2 -b :5000 main:app
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/assets:/code/assets
    ports:
      - "8080:8080"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
