version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/code
    ports:
      - "5000:5000"
    command: gunicorn -w 2 -b :5000 main:app
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/assets:/code/assets
      - ./frontend/dist:/code/dist
    command: npm run prodrun
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
